# Generated by Django 3.0.5 on 2020-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
