# Generated by Django 3.0.5 on 2020-05-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
