# Generated by Django 3.0.5 on 2020-05-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200515_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='ffname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='llname',
        ),
    ]
