# Generated by Django 3.0.5 on 2020-05-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200515_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ffname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='llname',
            new_name='lname',
        ),
    ]
