# Generated by Django 3.0.5 on 2020-05-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200515_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emaill',
        ),
    ]
