# Generated by Django 3.0.5 on 2020-05-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200515_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
