# Generated by Django 3.0.5 on 2020-05-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200525_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
