# Generated by Django 3.0.5 on 2020-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
