# Generated by Django 3.0.5 on 2020-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200525_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
