# Generated by Django 3.0.5 on 2020-05-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200525_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='filess',
            new_name='files',
        ),
    ]
