# Generated by Django 3.0.5 on 2020-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200526_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.FileField(upload_to='pics'),
        ),
    ]
